# Generated by Django 4.1.7 on 2023-03-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colonne',
            fields=[
                ('id_colonne', models.AutoField(primary_key=True, serialize=False)),
                ('titre_colonne', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'colonne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id_tache', models.AutoField(primary_key=True, serialize=False)),
                ('titre_tache', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tache',
                'managed': False,
            },
        ),
    ]
